apiVersion: v1
kind: Service
metadata:
  name: angular-realworld
spec:
  type: NodePort
  selector:
    app: angular-realworld
  ports:
    - port: 4200
      targetPort: 4200
      nodePort: 30100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-realworld
  labels:
    app: angular-realworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-realworld
  template:
    metadata:
      labels:
        app: angular-realworld
    spec:
      containers:
        - name: angular-realworld
          image: khalil15832/angular-realworld:latest
          ports:
            - containerPort: 4200
